Datetime validation
-------------------

Datetime validator parses using the python-dateutil library and
returns a python datetime object.

.. code-block:: python

    from strictyaml import Map, Datetime, YAMLValidationError, load
    from datetime import datetime
    from dateutil.tz.tz import tzutc
    
    schema = Map({
        "date": Datetime(),
        "datetime1": Datetime(),
        "datetime2": Datetime(),
        "datetime3": Datetime(),
    })

With variable 'valid_sequence':

.. code-block:: yaml

  date: 2016-10-22
  datetime1: 2016-10-22T14:23:12+00:00
  datetime2: 2016-10-22T14:23:12Z
  datetime3: 20161022T142312Z



.. code-block:: python

    load(valid_sequence, schema) == {
        "date": datetime(2016, 10, 22, 0, 0),
        "datetime1": datetime(2016, 10, 22, 14, 23, 12, tzinfo=tzutc()),
        "datetime2": datetime(2016, 10, 22, 14, 23, 12, tzinfo=tzutc()),
        "datetime3": datetime(2016, 10, 22, 14, 23, 12, tzinfo=tzutc()),
    }
    >>> True



.. code-block:: python

    load(valid_sequence, schema)["date"].text == "2016-10-22"
    >>> True

With variable 'invalid_sequence':

.. code-block:: yaml

  date: 1
  datetime1: Ã¢
  datetime2: b
  datetime3: c



.. code-block:: python

    load(invalid_sequence, schema)
    >>> EXCEPTION RAISED:
      when expecting a datetime
      found non-datetime
        in "<unicode string>", line 2, column 1:
          datetime1: "\xE2"
          ^ (line: 2)


Page automatically generated by hitchdoc from:
  hitch/datetime.story